sudo: required
dist: trusty
language: cpp
env:
  global:
  - PATH="/usr/local/cmake-3.13/bin:$PATH"

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - boost1.68
            - g++-8 
      env:
      - C_COMPILER=gcc-8
      - CXX_COMPILER=g++-8

    # - compiler: clang
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-trusty-3.8
    #       packages:
    #         - clang-3.8
    #   env:
    #   - C_COMPILER=clang-3.8
    #   - CXX_COMPILER=clang++-3.8

before_install:
 - wget -O cmake.sh https://cmake.org/files/v3.13/cmake-3.13.1-Linux-x86_64.sh 
 - sudo mkdir /usr/local/cmake-3.13
 - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local/cmake-3.13

script:
  - mkdir build
  - cd build
  - env CC=${C_COMPILER} CXX=${CXX_COMPILER} cmake .. -DCMAKE_BUILD_TYPE=Release
  - echo "We have" `nproc` "cores here"
  - make -j `nproc`
  - ctest -j `nproc` -V
